<?php
/**
 * @file
 * Interface module for talking with the materials backend.
 */

/**
 * This hook is run at the beginning of the page request
 */
function ding_material_type_preprocess_page(&$variables) {
  $path = current_path();
  $module_path = drupal_get_path('module', 'ding_material_type');

  if (strpos($path, 'ting/collection') === 0) {
    drupal_add_css($module_path . '/css/ding_material_type.styles.css');
  }
}
